fix:actions

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -15,14 +15,15 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Build the Docker image and run tests
-      run: docker compose -f "compose.test.yaml" up -d
+      run: |
+        docker-compose -f "compose.test.yaml" up -d || exit 1
 
     - name: Print Logs for Container
       run: |
-        export CONTAINER_ID=$(docker ps -aqf "name=ci")
-        docker logs -f $CONTAINER_ID | while read line ; do
-          echo $line
-          if echo $line | grep -qi 'FAILED'; then
+       export CONTAINER_ID=$(docker ps -aqf "name=ci")
+        docker logs -f "$CONTAINER_ID" | while read line ; do
+          echo "$line"
+          if echo "$line" | grep -qi 'FAILED'; then
             exit 1
           fi
         done
