update

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -20,8 +20,5 @@ jobs:
 
       - name: Print Logs for Container
         run: |
-          export CONTAINER_ID=$(docker ps -aqf "name=test_ci")
-          errors=$(docker logs -f $CONTAINER_ID 2>&1 | grep "FAILED" -c)
-          if [ $errors -gt 0 ]; then
-            exit 1
-          fi
+          export CONTAINER_ID=$(docker ps -aqf "name=ci") 
+          `docker logs -f $CONTAINER_ID 2>&1` | grep -i "FAILED" && exit 1 || exit 0
