rever

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -16,13 +16,9 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Build the Docker image and run tests
+        run: docker compose -f "backend/compose.test.yaml" up -d
+
+      - name: Print Logs for Container
         run: |
-          docker compose -f "backend/compose.test.yaml" up -d
-          export CONTAINER_ID=$(docker ps -aqf "name=ci")
-          if docker logs $CONTAINER_ID | grep -i "FAILED"; then
-            echo "Test failed. Exiting with status code 1."
-            exit 1
-          else
-            echo "Test passed. Exiting with status code 0."
-            exit 0
-          fi
+          export CONTAINER_ID=$(docker ps -aqf "name=ci") 
+          `docker logs -f $CONTAINER_ID` | grep -i "FAILED" && exit 1 || exit 0
