fix: added neccesary conditions to check for the failure

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -21,7 +21,13 @@ jobs:
       - name: Print Logs for Container
         run: |
           export CONTAINER_ID=$(docker ps -aqf "name=ci")
-          docker logs -f $CONTAINER_ID | exit 1
+          if docker logs $CONTAINER_ID | grep -i "FAILED"; then
+            echo "Test failed. Exiting with status code 1."
+            exit 1
+          else
+            echo "Test passed. Exiting with status code 0."
+            exit 0
+          fi
 
       - name: Stop and remove the Docker container
         run: docker compose -f "backend/compose.test.yaml" down
