fix: CI

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -15,10 +15,9 @@ jobs:
       uses: actions/checkout@v3
 
     - name: Build the Docker image and run tests
-      run: |
-        docker-compose -f "compose.test.yaml" up -d
+      run: docker compose -f "compose.test.yaml" up -d
 
     - name: Print Logs for Container
       run: |
-       export CONTAINER_ID=$(docker ps -aqf "name=ci")
-       `docker logs -f $CONTAINER_ID` | grep -i "FAILED" && exit 1 || exit 0
+        export CONTAINER_ID=$(docker ps -aqf "name=ci") 
+        `docker logs -f $CONTAINER_ID` | grep -i "FAILED" && exit 1 || exit 0
